add_newline = false

format = "$username ➜ $directory$git_branch$character"

[username]
show_always = true
format = "[$user]($style)"

[directory]
home_symbol = "~"
truncation_length = 2
truncate_to_repo = false
format = "[$path]($style)"

[git_branch]
format = " \\([$branch]($style)\\)"

[character]
format = " $symbol"
success_symbol = "\\$ "
error_symbol = "\\$ "
