version: "3"

dotenv: 
  - .env

vars:
  IMAGE: ghcr.io/{{.GITHUB_OWNER}}/{{.IMAGE_NAME}}
  TAG:
    sh: git rev-parse --short HEAD

tasks:
  default:
    silent: true
    cmds:
      - task --list --sort none
      
  build:
    desc: Build container image
    cmds:
      - docker build -t {{.IMAGE}}:{{.TAG}} -t {{.IMAGE}}:latest .

  push:
    desc: Push container image to GitHub Container Registry
    deps:
      - build
    cmds:
      - docker push {{.IMAGE}}:{{.TAG}}
      - docker push {{.IMAGE}}:latest

  login:
    cmds:
      - echo "$GITHUB_TOKEN" | docker login ghcr.io -u {{.GITHUB_USER}} --password-stdin

  release:
    desc: Build and push container image
    deps:
      - login
      - push
