version: "3"

vars:
  GITHUB_OWNER: umajin
  IMAGE_NAME: devcontainer
  IMAGE: ghcr.io/{{.GITHUB_OWNER}}/{{.IMAGE_NAME}}

  TAG:
    sh: git rev-parse --short HEAD

tasks:
  default:
    silent: true
    cmds:
      - task --list --sort none

  build:
    desc: Build container image
    cmds:
      - docker build \
          -t {{.IMAGE}}:{{.TAG}} \
          -t {{.IMAGE}}:latest \
          .

  run:
    desc: Run container image locally
    deps:
      - build
    cmds:
      - docker run --rm -it {{.IMAGE}}:{{.TAG}}