name: Validate Features

on:
  pull_request:
    paths:
      - "features/**"

  push:
    branches:
      - main
    paths:
      - "features/**"

jobs:
  validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Validate features
        uses: devcontainers/action@v1
        with:
          cmd: features validate
          features: features/src